### ISSUE TITLE
Travis Credential issues... still :(

### ISSUE THREAD

**Issue by petems** [voxpupuli/puppet-redis#267]
@arioch Still happening I'm afraid:

https://travis-ci.org/arioch/puppet-redis/jobs/394058880

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/puppet-blacksmith-4.1.2/lib/puppet_blacksmith/forge.rb:49:in `rescue in push!': Error login to the forge https://forgeapi.puppetlabs.com as arioch [400 Bad Request]: {"error":"invalid_grant","error_description":"Username/password do not match"} (Blacksmith::Error)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/puppet-blacksmith-4.1.2/lib/puppet_blacksmith/forge.rb:40:in `push!'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-puppet_forge-1.9.7/lib/dpl/provider/puppet_forge.rb:39:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.7/lib/dpl/provider.rb:195:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.7/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.7/lib/dpl/provider.rb:195:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.7/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.7/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.9.7/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:23:in `<main>'
failed to deploy
```

**Comment by arioch** [comment]
Sent you a pm.

**Comment by petems** [comment]
No longer an issue, moved to Vox 👍
